---
title: "Analytic Dataset"
author: "Sarahy Martinez"
date: "2024-11-16"
output: github_document
---

This document for cleaning and tidying the data.

```{r, message=FALSE}
library(tidyverse)
library(rvest)
library(sf)
library(purrr)
``` 

```{r, message=FALSE}
nineteen_twentyone_county_lyme = read_csv("new_york_county_lyme.csv") %>% 
  janitor::clean_names() %>% 
  select(county_name, event_count,percent_rate ) %>% 
  rename(NAME = "county_name") %>% 
  mutate( data = "lyme")

print(nineteen_twentyone_county_lyme)

```


Tidy deer tick data 
```{r, message=FALSE}

tick_surveillance = read_csv("./Deer_Tick_Surveillance__Adults__Oct_to_Dec__excluding_Powassan_virus__Beginning_2008_20241116.csv") %>% 
  janitor::clean_names() %>% 
  filter(year %in% 2019:2021 ) %>% 
  rename(NAME = "county") %>% 
  select(-total_sites_visited, -school_districts_2016_shp, -local_waterfront_revitalization_program_lwrp_communities, -new_york_zip_codes, -counties, -nys_senate_districts, -year) %>% 
mutate(data = "ticks")


print(tick_surveillance)

```

Read in shp file for NY counties 

```{r, message=FALSE}
ny_county =  st_read("./Counties.shp") 

print(ny_county)

```

Merging the data sets 

```{r, message=FALSE}

# merging the excel sheets first 

NY_lyme_tick = full_join(tick_surveillance, nineteen_twentyone_county_lyme, by = "NAME") %>% 
  select(-data.x, -data.y)

print(NY_lyme_tick)
# now merging the shape file with excel file 

NY_lyme_tick_county = NY_lyme_tick %>%
  left_join(ny_county, by = "NAME") %>% 
  janitor::clean_names()
# didn't delete the other parts from abbrev and later because they are part of the shapefile and if I delete I have to convert it to a dataframe making the shapefile no longer spatial. 

print(NY_lyme_tick_county)

```

