---
title: "Data Visuals 2020"
author: "Tanmayi Amanchi"
date: "2024-11-23"
output: html_document
runtine: shiny
---

This document for visualizing the cleaned/tidied data set.The beginning of this code is a repeat of the tidied data from Data Preparation. This was performed again since there was an issue in the geometry  of the final_data.csv. So we will be working with a data set called tick_lyme_weather with proper geometry attributes needed to make maps.
```{r, message=FALSE}
#Load the necessary libraries 
library(tidyverse)
library(rvest)
library(sf)
library(purrr)
library(knitr)
library(dplyr)
library(ggplot2)
library(sf)
library(leaflet)
library(tigris)
options(tigris_use_cache = TRUE)
``` 

```{r, message=FALSE}
#Read in lyme dataset and select necessary variables
nineteen_twentyone_county_lyme = read_csv("new_york_county_lyme.csv") %>%  #read in the NYC lyme data
  janitor::clean_names() %>%  #clean the names 
  select(county_name, event_count,percent_rate ) %>%  # select variables of interest 
  rename(NAME = "county_name", 
         lyme_count = "event_count",
         lyme_rate = "percent_rate"
         ) %>%  # renaming so we can have a common variable when merging 
  mutate( data = "lyme") # created a new variable so double check that merging was accurate

print(nineteen_twentyone_county_lyme)

```
