---
title: "Data Visuals"
author: "Tanmayi Amanchi"
date: "2024-11-23"
output: 
  html_document:
    toc: true
    toc_float: true
---

This document for visualizing the cleaned/tidied data set.The beginning of this code is a repeat of the tidied data from Data Preparation. This was performed again since there was an issue in the geometry  of the final_data.csv. So we will be working with a data set called tick_lyme_weather with proper geometry attributes needed to make maps.
```{r, message=FALSE}
#Load the necessary libraries 
library(tidyverse)
library(rvest)
library(sf)
library(purrr)
library(knitr)
library(dplyr)
library(ggplot2)
library(sf)
library(leaflet)
library(tigris)
options(tigris_use_cache = TRUE)
``` 

```{r, message=FALSE}
#Read in lyme dataset and select necessary variables
nineteen_twentyone_county_lyme = read_csv("new_york_county_lyme.csv") %>%  #read in the NYC lyme data
  janitor::clean_names() %>%  #clean the names 
  select(county_name, event_count,percent_rate ) %>%  # select variables of interest 
  rename(NAME = "county_name", 
         lyme_count = "event_count",
         lyme_rate = "percent_rate"
         ) %>%  # renaming so we can have a common variable when merging 
  mutate( data = "lyme") # created a new variable so double check that merging was accurate

print(nineteen_twentyone_county_lyme)

```

```{r, message=FALSE}
#Read in tick data set and remove unnecessary variables 
tick_surveillance = read_csv("./Deer_Tick_Surveillance__Adults__Oct_to_Dec__excluding_Powassan_virus__Beginning_2008_20241116.csv") %>% 
  janitor::clean_names() %>% # clean the names so they follow normal form 
  filter(year %in% 2019:2021 ) %>%  # filtering from the years of interest that are based from the lyme disease data 
  rename(NAME = "county") %>% # renaming for common identifier
  rename(ticks_tested = "total_tested") %>% 
  select(-total_sites_visited, -school_districts_2016_shp, -local_waterfront_revitalization_program_lwrp_communities, -new_york_zip_codes, -counties, -nys_senate_districts, -a_phagocytophilum_percent, -b_microti_percent, -b_miyamotoi_percent) %>%  # selecting and removing variables of interest , 
mutate(data = "ticks")  # adding a variable to identify merging 

print(tick_surveillance)
```

```{r, message=FALSE}
#Read in shp file for NY counties to use for heatmap and county level data
ny_county =  st_read("./Counties.shp")  
```

```{r, message=FALSE}
# Merging the tick and lyme data set  
NY_lyme_tick = full_join(tick_surveillance, nineteen_twentyone_county_lyme, by = "NAME") %>% 
  select(-data.x, -data.y)

# Merging the shape file with this combined file
NY_lyme_tick_county = NY_lyme_tick %>%
  left_join(ny_county, by = "NAME") %>% 
  janitor::clean_names() 
```

```{r}
#Merging and reading in average temperature csv with data from Jan19 to Dec22
ny_temp = read_csv("./avg_temp_county.csv", skip =1) %>% 
  janitor::clean_names() %>% 
  select(county:dec_22) %>% 
mutate(county = str_replace_all(county, "(?i) county$", "")) %>% #Mutated to remove the suffix county so that the data can be merged and have common identifier
  rename(name = "county") %>%  #Renaming to have common identifier 
  drop_na(name) #There are two rows with entirely no data they are dropped 

tick_lyme_weather = NY_lyme_tick_county  %>% #Merging the entire data set with avg weather 
  left_join(ny_temp, by = "name") %>% 
  janitor::clean_names() 
```
