---
title: "Analytic Dataset"
author: "Sarahy Martinez"
date: "2024-11-16"
output: github_document
---

This document for cleaning and tidying the data.

```{r, message=FALSE}
library(tidyverse)
library(rvest)
library(sf)
library(purrr)
library(knitr)
library(readxl)
``` 

```{r, message=FALSE}
nineteen_twentyone_county_lyme = read_csv("new_york_county_lyme.csv") %>%  #read in the NYC lyme data
  janitor::clean_names() %>%  #clean the names 
  select(county_name, event_count,percent_rate ) %>%  # select variables of interest 
  rename(NAME = "county_name", 
         lyme_count = "event_count",
         lyme_rate = "percent_rate"
         ) %>%  # renaming so we can have a common variable when merging 
  mutate( data = "lyme") # created a new variable so double check that merging was accurate

print(nineteen_twentyone_county_lyme)

```


Tidy deer tick data 
```{r, message=FALSE}

tick_surveillance = read_csv("./Deer_Tick_Surveillance__Adults__Oct_to_Dec__excluding_Powassan_virus__Beginning_2008_20241116.csv") %>% 
  janitor::clean_names() %>% # clean the names so they follow normal form 
  filter(year %in% 2019:2021 ) %>%  # filtering from the years of interest that are based from the lyme disease data 
  rename(NAME = "county") %>% # renaming for common identifier
  rename(ticks_tested = "total_tested") %>% 
  select(-total_sites_visited, -school_districts_2016_shp, -local_waterfront_revitalization_program_lwrp_communities, -new_york_zip_codes, -counties, -nys_senate_districts, -a_phagocytophilum_percent, -b_microti_percent, -b_miyamotoi_percent) %>%  # selecting and removing variables of interest , 
mutate(data = "ticks")  # adding a variable to identify merging 


print(tick_surveillance)

```

Read in shp file for NY counties 

```{r, message=FALSE}
ny_county =  st_read("./Counties.shp")  # read in the county shapefile 
 
print(ny_county)

```

Merging the data sets 

```{r, message=FALSE}

# merging the excel sheets first 

NY_lyme_tick = full_join(tick_surveillance, nineteen_twentyone_county_lyme, by = "NAME") %>% 
  select(-data.x, -data.y)

print(NY_lyme_tick)
# now merging the shape file with excel file 

NY_lyme_tick_county = NY_lyme_tick %>%
  left_join(ny_county, by = "NAME") %>% 
  janitor::clean_names() 

# didn't delete the other parts from abbrev and later because they are part of the shapefile and if I delete I have to convert it to a dataframe making the shapefile no longer spatial. 


```



```{r}
# merging and reading in tammy csv file with avg temps 

ny_temp = read_csv("./avg_temp_county.csv", skip =1) %>% 
  janitor::clean_names() %>% 
  select(county:dec_22) %>% 
mutate(county = str_replace_all(county, "(?i) county$", "")) %>% #mutated to remove the suffix county so that the data can be merged and have common identifier
  rename(name = "county") %>%  # renaming to have common identifier 
  drop_na(name) # there are two rows with entirely no data so I dropped them 

tick_lyme_weather = NY_lyme_tick_county  %>% # now merging the entire dataset with avg weather 
  left_join(ny_temp, by = "name") %>% 
  janitor::clean_names() 

         
# Average temperature across counties in 2019
  nineteen = tick_lyme_weather %>% 
    select(year:dec_19) %>% 
    filter(year == 2019 ) %>% 
    mutate(avg_temp = rowMeans(select(., jan_19:dec_19), na.rm = TRUE)) %>% 
    select( everything(), -jan_19, -feb_19, -mar_19, -apr_19, -may_19,-jun_19, -jul_19, -aug_19, -sep_19, -oct_19, -nov_19, -dec_19)
  
  twenty =  tick_lyme_weather %>% 
    select(everything(), -jan_19, -feb_19, -mar_19, -apr_19, -may_19,-jun_19, -jul_19, -aug_19, -sep_19, -oct_19, -nov_19, -dec_19, -jan_21, -feb_21, -mar_21, -apr_21, -may_21,-jun_21, -jul_21, -aug_21, -sep_21, -oct_21, -nov_21, -dec_21, -jan_22, -feb_22, -mar_22, -apr_22, -may_22,-jun_22, -jul_22, -aug_22, -sep_22, -oct_22, -nov_22, -dec_22) %>% 
    filter(year == 2020) %>% 
    mutate(avg_temp = rowMeans(select(., jan_20:dec_20), na.rm = TRUE)) %>% 
    select( everything(), -jan_20, -feb_20, -mar_20, -apr_20, -may_20,-jun_20, -jul_20, -aug_20, -sep_20, -oct_20, -nov_20, -dec_20)
  
    
  twenty_one = tick_lyme_weather %>% 
    select(everything(), -jan_19, -feb_19, -mar_19, -apr_19, -may_19,-jun_19, -jul_19, -aug_19, -sep_19, -oct_19, -nov_19, -dec_19, -jan_20, -feb_20, -mar_20, -apr_20, -may_20,-jun_20, -jul_20, -aug_20, -sep_20, -oct_20, -nov_20, -dec_20, -jan_22, -feb_22, -mar_22, -apr_22, -may_22,-jun_22, -jul_22, -aug_22, -sep_22, -oct_22, -nov_22, -dec_22) %>% 
    filter(year == 2021) %>% 
    mutate(avg_temp = rowMeans(select(., jan_21:dec_21), na.rm = TRUE)) %>% 
    select( everything(), -jan_21, -feb_21, -mar_21, -apr_21, -may_21,-jun_21, -jul_21, -aug_21, -sep_21, -oct_21, -nov_21, -dec_21)
  
  # concerning because there is no data for the year 2022
  twenty_two =  tick_lyme_weather %>% filter(year == 2022)
 

  #then once we get the get avg per year then merge them together


   
# average temperatures by year by county 
# get yearly by summing the year and finding the average 
         
```

# Saved Final Dataset 

```{r}
write_csv(tick_lyme_weather, "final_data.csv")

tidied = read_csv("final_data.csv")
```





