---
title: "Deliverable 1: Team & Proposal"
author: "Mary Williams, Sarahy Martinez, Tanmayi Amanchi, Kaleb Frierson"
date: "2024-10-28"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
---

## The group members (names and UNIs)

Mary Williams, mnw2132
Sarahy Martinez, sjm2284
Tanmayi Amanchi, taa2158
Kaleb Frierson, kjf2152

## The tentative project title

Distribution of West-nile virus and associated risk factors in NYC. 

## The motivation for this project

- To determine if neighborhoods with lower rates of vector control have higher rates of west-nile virus detection among mosquito's? 

- To investigate whether weather (precipitation, temp, humidity) influence West-nile virus in NYC?

- To observe various geographic distributions of disease and disease risk factors throughout NYC. 

## The intended final products

- Heat maps, density maps, scatter plots, and other graphical visual aids demonstrating geospatial trends and prevalence of disease and disease risk factors. 

- Tables presenting general statistics.

- Statistical findings like causative tests/regression outputs. 

- Project website reporting our findings including our screen cast. 

## The anticipated data sources

- NYC DOHMH, NYC DEP, NYS DOH, EPA, Data.gov

## The planned analyses / visualizations / coding challenges

- Analyses
  - Exploratory Analyses
  - Regression/correlation 
  
- Visualizations
  - Heat Maps
  - Density Maps
  - Scatter Plots
  - Box Plots
  - Tables

- Coding Challenges
  - Deciding on a analytic dataset and producing it will be difficult. 
  - Collaborative work is challenging, especially as we learn github and how to work on the same space in R Studio. 
  - In this class, we haven't learned statistical analysis so we will be drawing on our own knowledge/interests. 
  - Never made a heat map in R before. 
  - Making maps in general requires geo-data that we might not be able to line up with our data sources. 
  - West nile virus data sources could be incomplete or not UTD. 

## The planned timeline

- November 11-15	Project review meeting	Zoom meeting – no “deliverable”

- December 7 by 11:59 pm	Report	Written report giving detailed project description

- December 7 by 11:59 pm	Webpage and screencast	Webpage overview of project, with short explanatory video (published online)

- December 7 by 11:59 pm	Peer assessment	Brief assessment of your teammates contributions (as a short document)

- December 12	“In class” discussion of projects	Enjoy hearing about projects! (Also get hex stickers…)
